// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBX8jdeYpzFZUxmalfW3_NRL2NWc3WA98',
    appId: '1:29158914377:web:67b8e3b50ad3f98dec8298',
    messagingSenderId: '29158914377',
    projectId: 'uber-flutter-27c11',
    authDomain: 'uber-flutter-27c11.firebaseapp.com',
    storageBucket: 'uber-flutter-27c11.firebasestorage.app',
    measurementId: 'G-BJFWZFFWJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnlPYvRGcgy2CpfzvOlmbowPlbp42_vrs',
    appId: '1:29158914377:android:ce0645ab588acf55ec8298',
    messagingSenderId: '29158914377',
    projectId: 'uber-flutter-27c11',
    storageBucket: 'uber-flutter-27c11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFDKchHLvkq3kUJ_xZqnFr4Urhy4ZhBMY',
    appId: '1:29158914377:ios:044d6d459378cb78ec8298',
    messagingSenderId: '29158914377',
    projectId: 'uber-flutter-27c11',
    storageBucket: 'uber-flutter-27c11.firebasestorage.app',
    iosBundleId: 'com.example.uberFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFDKchHLvkq3kUJ_xZqnFr4Urhy4ZhBMY',
    appId: '1:29158914377:ios:044d6d459378cb78ec8298',
    messagingSenderId: '29158914377',
    projectId: 'uber-flutter-27c11',
    storageBucket: 'uber-flutter-27c11.firebasestorage.app',
    iosBundleId: 'com.example.uberFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBX8jdeYpzFZUxmalfW3_NRL2NWc3WA98',
    appId: '1:29158914377:web:3d3ab0199011e810ec8298',
    messagingSenderId: '29158914377',
    projectId: 'uber-flutter-27c11',
    authDomain: 'uber-flutter-27c11.firebaseapp.com',
    storageBucket: 'uber-flutter-27c11.firebasestorage.app',
    measurementId: 'G-838P235C8N',
  );
}
